import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppStateProvider } from "@/components/AppStateProvider";
import { Navbar } from "@/components/Navbar";
import { PlayerBar } from "@/components/PlayerBar";
import { QueuePanel } from "@/components/QueuePanel";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-black text-white">
        <AppStateProvider>
          {/* The root layout is where shared UI lives so the navbar and player stay visible on every page. */}
          <Navbar />

          {/* This wrapper keeps page content above the fixed player bar at the bottom. */}
          <div className="flex min-h-full flex-col pb-56 md:pb-32">
            {children}
          </div>

          {/* The player bar and queue are separate fixed elements so neither creates a large overlay. */}
          <PlayerBar />
          <QueuePanel />
        </AppStateProvider>
      </body>
    </html>
  );
}
